# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - mlflow-image/mlflow_version
    - infrastructure
resources:
  repositories:
    - repository: templates
      type: git
      name: "Smart Data/pipeline_templates"
      ref: refs/tags/v0.9.5

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: tofu
    displayName: "Check that OpenTofu plan is up to date"
    steps: 
      - template: tofu-check.yaml@templates
        parameters:
          infrastructure_folder: "infrastructure"
          aws_credentials: "AWS mlops"
  - job: build_mlflow
    displayName: "Build MLflow"
    variables:
      DOCKER_IMAGE: "mlflow"
      ECR_REPOSITORY: "dna/mlflow"
    steps:
    - bash: |
        MLFLOW_VERSION=$(cat ./mlflow-image/mlflow_version)
        echo $MLFLOW_VERSION
        echo "##vso[task.setvariable variable=mlflow_tag;isOutput=true]$MLFLOW_VERSION"
      name: mlflow_version
      displayName: "Read MLflow version"
    
    - template: docker-build-cache.yaml@templates
      parameters:
        docker_image_name: $(DOCKER_IMAGE)
        dockerfile_path: "mlflow-image/Dockerfile"
        docker_build_context: "mlflow-image"
        additional_docker_build_args: "--tag $(DOCKER_IMAGE):$(mlflow_version.mlflow_tag)"
    
    - task: ECRPushImage@1
      inputs:
        awsCredentials: "ECR Push"
        regionName: "eu-central-1"
        imageSource: "imagename"
        sourceImageName: "$(DOCKER_IMAGE)"
        repositoryName: "$(ECR_REPOSITORY)"
        pushTag: "$(mlflow_version.mlflow_tag)"
      displayName: "Push mlflow image"
    
    - task: ECRPushImage@1
      inputs:
        awsCredentials: "ECR Push"
        regionName: "eu-central-1"
        imageSource: "imagename"
        sourceImageName: "$(DOCKER_IMAGE)"
        repositoryName: "$(ECR_REPOSITORY)"
        pushTag: "$(mlflow_version.mlflow_tag)"
      displayName: "Push mlflow image with version tag"
    - publish: 'infrastructure'
      artifact: 'tf'
